class AnimationConfig:

    FIREBALL_RADIUS = 18
    FIREBALL_SPEED = 20
    FIREBALL_TRAIL = 15

    LIGHTNING_RADIUS = 30
    LIGHTNING_POINTS = 8

    ICE_BEAM_LENGTH = 250

    LASER_LENGTH = 800

    SHIELD_RADIUS = 80

    SPIDER_MAX_DISTANCE = 400
    SPIDER_TRAIL = 20